name: supply-chain security - Cargo audit
on: 
  branch_protection_rule:
  schedule:
    - cron: '42 12 * * 2'
  push:
    branches: [ master ]

permissions: read-all

jobs:
  run-security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
