name: Release new packages

on:
  workflow_dispatch:
    inputs:
      reason:
        description: Reason for deployment
        required: true

  push:
    tags:
      - "v*"

permissions:
  contents: write


jobs:
  publish-crate-on-new-release:
    name: "Publish crate on Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - uses: katyo/publish-crates@v1
        with:
            registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      
      - name: create-new-release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            CHANGELOG.md
            README.md
            COPYRIGHT
            SECURITY.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
